// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDduP111aepVEdXKZP8Muu8xEfNVBSnvng',
    appId: '1:950200397496:web:7312991822c79f4ca20e4d',
    messagingSenderId: '950200397496',
    projectId: 'capstone-403203',
    authDomain: 'capstone-403203.firebaseapp.com',
    storageBucket: 'capstone-403203.appspot.com',
    measurementId: 'G-X6C4TRL5RY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCehnjAE6feqnJi8uuAZb6Sl5wuOjakAPY',
    appId: '1:950200397496:android:24e004e0f50b0cbda20e4d',
    messagingSenderId: '950200397496',
    projectId: 'capstone-403203',
    storageBucket: 'capstone-403203.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAhNNrObvTlpZ3chIAWxf-JtjggnvmnUC8',
    appId: '1:950200397496:ios:d44cfa3b12ed138fa20e4d',
    messagingSenderId: '950200397496',
    projectId: 'capstone-403203',
    storageBucket: 'capstone-403203.appspot.com',
    androidClientId: '950200397496-fmlkdt3trse7tr418v0a9advt3fsag2o.apps.googleusercontent.com',
    iosClientId: '950200397496-su9lvmd6j0usdq8g8jgbsum77krm1e67.apps.googleusercontent.com',
    iosBundleId: 'com.example.gradient3',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAhNNrObvTlpZ3chIAWxf-JtjggnvmnUC8',
    appId: '1:950200397496:ios:bb6c60bb79b5e2eda20e4d',
    messagingSenderId: '950200397496',
    projectId: 'capstone-403203',
    storageBucket: 'capstone-403203.appspot.com',
    androidClientId: '950200397496-fmlkdt3trse7tr418v0a9advt3fsag2o.apps.googleusercontent.com',
    iosClientId: '950200397496-vdngof3gv5n20qu1155480kviilbmcig.apps.googleusercontent.com',
    iosBundleId: 'com.example.gradient3.RunnerTests',
  );
}
